[font]
size = 12.0

[font.bold]
family = "0xProto Nerd FontMono"
style = "Bold"

[font.italic]
family = "0xProto Nerd FontMono"
style = "Italic"

[font.normal]
family = "0xProto Nerd FontMono"
style = "Regular"
